// ///<reference types="react" />

// declare module "zustand/DashBoard";
// declare module "zustand/useItemStore";
// declare module "zustand/useUserStore";
// declare module "jotai/useItemStore";
// declare module "ui/Menu";
// declare module "ui/Flex";
// declare module "ui/Grid";
// declare module "ui/Box";
// declare module "ui/Container";
// declare module "ui/Section";
// declare module "ui/Header";
// declare module "ui/Footer";
// declare module "ui/Button";
// declare module "ui/Inset";
// declare module "ui/Theme";
// declare module "ui/Table";
// declare module "ui/Text";
// declare module "ui/TextField";
// declare module "ui/Card";
// declare module "ui/Spinner";
// declare module "ui/LandingBackground";
// declare module "ui/CheckBoxCard";
// declare module "ui/MainContainer";
// declare module "ui/MainArchitecture";
// declare module "ui/Blockquote";
// declare module "axios/instance";
// declare module "auth/Login";
// declare module "auth/Landing";
// declare module "auth/useUser";
// declare module "auth/ProtectedRoute";
// declare module "reactQuery/queryClient";
// declare module "reactQuery/CommentData";
// declare module "error/ErrorBoundary";
// declare module "model/user.interface";

// declare module "*.jpg";
// declare module "@/*";
